### PR TITLE
Update Cargo.toml

### PR DESCRIPTION
**Pull request by ttys3**

### CODE REVIEW

**Comment by wusyong** [comment]
@qdot Hello! Thanks for this crate! Gtk has published v0.14 and I'm trying to update their deps.
Do you have some time to merge this PR? I could also open another PR in libappindicator-rs if new version of this sys crate is published.

**Comment by qdot** [comment]
Oof, totally missed this PR for some reason. Sure, I'll try to get this done in the next day or two.

**Comment by Absolucy** [comment]
erm, is this going to be merged?

**Comment by wusyong** [comment]
Hey I merged the change in #17, but I'm going to merge this crate into libappindicator too.
I'll archive this once it's done

**Pull request closed without merging**
