### PR TITLE
Update gtk-sys, bindgen,pkg-config

### PR DESCRIPTION
**Pull request by xVanTuring**

### CODE REVIEW

**Comment by xVanTuring** [comment]
I also update the `libappindicator-rs` package, which will be available after  merging and updating on `crate.io`

**Comment by jonhoo** [comment]
This update is now critical @qdot, since the old version of `bindgen` no longer builds on `stable`. There is an even newer version of `bindgen` we may want to adopt if we're going to do a new release anyway.

**Comment by qdot** [comment]
@jonhoo @xVanTuring All done! Brought in patches, bumped and published version 0.4.0 of the crate. Sorry it took, uh, multiple years.

**Comment by jonhoo** [comment]
@qdot Excellent, thank you! Better late than never :p You may want to just bump the latest `bindgen` while you're at it (and maybe other deps too? `cargo outdated` should tell you) Could you do a bump for `libappindicator-rs` too so the changes propagate downstream?

**Pull request merged**
